preprocessing:
  classes:
  - toxic
  - severe_toxic
  - obscene
  - threat
  - insult
  - identity_hate
  embedding_dim: 100
  input_convertor: nn_vectorization
  input_id_column: id
  input_testset: ./data/test.csv
  input_text_column: comment_text
  input_trainset: ./data/train.csv
  max_len: 128
  pretrained_embedding: ./data/glove.twitter.27B.100d.txt
  random_seed: 0
  split_ratio: 0.3
training:
  batch_normalization: true
  batch_size: 32
  dropout_rate: 0.1
  embedding_dim: 100
  epochs: 1
  ff_dim: 128
  gradient_cliping: true
  learning_rate: 0.8
  max_len: 128
  model_name: transformer
  num_heads: 1
  optimizer: sgd
predict:
  output_path: ./data/submission.csv
